### ISSUE TITLE
Can we export model to onnx ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [saic-vul/iterdet#21]
Hi,

Thank for your excellent work. 
I saw that you have a file pytorch2onnx.py in ./tools. But when i used it, i got an error: 

File "/mmdet/models/detectors/two_stage.py", line 88, in forward_dummy

 x = self.extract_feat(img)

TypeError: extract_feat() missing 1 required positional argument: 'history'

Please help me in this case how to find and add "history".  

Best regard

**Comment by hoangkhoiLEds2019** [comment]
`python` pytorch2onnx.py --config  wider_person_faster_rcnn_r50_fpn_2x.py --checkpoint wider_person_faster_rcnn_r50_fpn_2x.pth   --out  wider_person_faster_rcnn_r50_fpn_2x.onnx
/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py:209: UserWarning: `add_node_names' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `add_node_names` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py:209: UserWarning: `do_constant_folding' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `do_constant_folding` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
Traceback (most recent call last):
  File "pytorch2onnx.py", line 125, in <module>
    main()
  File "pytorch2onnx.py", line 117, in main
    onnx_model = export_onnx_model(model, (input_data, ), args.passes)
  File "pytorch2onnx.py", line 44, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 334, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 291, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py", line 278, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py", line 361, in forward
    self._force_outplace,
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py", line 348, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/mmdet/models/detectors/two_stage.py", line 88, in forward_dummy
    x = self.extract_feat(img)
TypeError: extract_feat() missing 1 required positional argument: 'history'
 `

**Comment by hoangkhoiLEds2019** [comment]
![image](https://user-images.githubusercontent.com/57557628/91158465-f2d24100-e6c6-11ea-9804-adaa3e9f2092.png)

**Comment by filaPro** [comment]
Hi @hoangkhoiLE,

Unfortunately I'm not familiar with `onnx` and this script is here as we forked from original [mmdetection](https://github.com/open-mmlab/mmdetection). In this particular place the problem is that we overwrite [forward_train](https://github.com/saic-vul/iterdet/blob/master/mmdet/models/detectors/iterdet_faster_rcnn.py#L40) method, but not [forward_dummy](https://github.com/saic-vul/iterdet/blob/master/mmdet/models/detectors/two_stage.py#L81). Looks like it also need a one line modification to use `history` argument.

**Comment by hoangkhoiLE** [comment]
Thank you for your answer. I try to overwrite forward_dummy by the way you do with foward_train. But it is not working, i'm looking forward to your suggestion to modify it. Thank a lot 

Here is how i tried:

    def forward_dummy(self, img, history=None):
        """Used for computing network flops.

        See `mmdetection/tools/get_flops.py`
        """
        outs = ()
        # backbone
        x = self.extract_feat(img,history)
        # rpn
        if self.with_rpn:
            rpn_outs = self.rpn_head(x)
            outs = outs + (rpn_outs, )
        proposals = torch.randn(1000, 4).to(img.device)
        # roi_head
        roi_outs = self.roi_head.forward_dummy(x, proposals)
        outs = outs + (roi_outs, )
        return outs

![image](https://user-images.githubusercontent.com/57557628/91172796-143e2780-e6dd-11ea-81bf-b36d22d26957.png)

Best regard.

**Comment by filaPro** [comment]
Looks like [here](https://github.com/saic-vul/iterdet/blob/master/tools/pytorch2onnx.py#L113) `input_data` should be a tuple ((1, 3, w, h), (1, 1, w, h)). Now it contains only image and the history is `None`, so you are getting this `NoneType` exception.

**Comment by hoangkhoiLE** [comment]
Thank for your response. I will try to fix it.

**Comment by rh-ia** [comment]
Dear @filaPro @hoangkhoiLE ,

I was able to generate an .onnx model file by overwriting `forward_dummy` as follows, inspired by your discussion:
```
def forward_dummy(self, img, history=None):
    """Used for onnx model file.
    See `mmdetection/tools/pytorch2onnx.py`
    """
    if not history:
        height, width = img.shape[2:]
        history = torch.zeros((1, 1, height, width), device=img.device)
    x = self.extract_feat(img, history)
    outs = self.bbox_head(x)
    return outs
```
Which I wrote in `mmdet/models/detectors/iterdet_retinanet.py`. 

KR
